import numpy as np
import tiktoken
from typing import List
from dotenv import load_dotenv
from openai import OpenAI


# Load environment variables (including OPENAI_API_KEY)
load_dotenv()

# Create OpenAI API client
client = OpenAI()


# Embedding configuration
EMBED_MODEL = "text-embedding-3-small"
EMBED_DIMS = 1536

# Maximum tokens allowed for a single input
MAX_INPUT_TOKENS = 8191

# Our own batch limit.
# We keep it below the API's maximum to leave some safety margin.
BATCH_TOKEN_BUDGET = 100_000


# Tokenizer used to count tokens before sending text to the API
_enc = tiktoken.get_encoding("cl100k_base")


def n_tokens(text: str) -> int:
    """Return the number of tokens in the given text."""
    return len(_enc.encode(text))


def embed_batch(texts: List[str]) -> np.ndarray:
    """
    Convert multiple texts into embeddings.

    Returns:
        NumPy array of shape:
        (number_of_texts, embedding_dimensions)
    """

    # Make sure no individual text exceeds the embedding API's limit.
    # Large text should be chunked before reaching this function.
    for t in texts:
        if n_tokens(t) > MAX_INPUT_TOKENS:
            raise ValueError(
                f"input has {n_tokens(t)} tokens > "
                f"{MAX_INPUT_TOKENS}; chunk it first"
            )

    # Stores all embeddings generated by the API
    out: List[List[float]] = []

    # Current batch and its total token count
    batch = []
    batch_tokens = 0

    def flush():
        """
        Send the current batch to the Embeddings API
        and add the returned vectors to 'out'.
        """
        nonlocal batch, batch_tokens

        # Nothing to send
        if not batch:
            return

        # One API call can generate embeddings for multiple texts
        resp = client.embeddings.create(
            model=EMBED_MODEL,
            input=batch
        )

        # Extract embeddings from the response.
        # The order matches the input order.
        out.extend(d.embedding for d in resp.data)

        # Start a fresh batch
        batch = []
        batch_tokens = 0

    # Build batches based on TOKEN count, not number of texts.
    for t in texts:
        tk = n_tokens(t)

        # If adding this text would exceed our batch budget,
        # send the current batch first.
        if batch_tokens + tk > BATCH_TOKEN_BUDGET:
            flush()

        batch.append(t)
        batch_tokens += tk

    # Send the final batch
    flush()

    # Convert the list of vectors into a NumPy array
    return np.array(out, dtype=np.float32)


def embed_one(text: str) -> np.ndarray:
    """Generate an embedding for a single text."""
    return embed_batch([text])[0]


if __name__ == "__main__":

    # Example texts we want to convert into embeddings
    texts = [
        "How do I request a refund?",
        "Can I return my purchase for money back?",
        "The mitochondrion is the powerhouse of the cell.",
        "What is the process for getting my money back?",
    ]

    # Generate embeddings for all four texts
    vecs = embed_batch(texts)

    # Example:
    # 4 texts × 1536 dimensions
    print("shape:", vecs.shape)

    # Each vector contains float32 values
    print("dtype:", vecs.dtype)

    # Check whether the embeddings are unit-normalized.
    # OpenAI embeddings are normalized, so the values should be ~1.0.
    print(
        "norms:",
        np.round(np.linalg.norm(vecs, axis=1), 4)
    )

    # Print only the first 6 values of the first embedding
    # instead of printing all 1536 values.
    print(
        "first 6 values of vector 0:",
        np.round(vecs[0][:6], 4)
    )

    # Compare every embedding with the first embedding.
    #
    # vecs[0] = "How do I request a refund?"
    #
    # Since the embeddings are normalized, dot product can
    # be used as a similarity score.
    sims = vecs @ vecs[0]

    # Pair each text with its similarity score and sort
    # from highest similarity to lowest.
    for text, similarity in sorted(
        zip(texts, sims),
        key=lambda x: -x[1]
    ):
        print(f"  {similarity:.4f}  {text}")

# texts
#   ↓
# embed_batch()
#   ↓
# Embedding API
#   ↓
# vectors
#   ↓
# compare vectors
#   ↓
# find similar text